language: r
cache: packages

matrix:
  include:
    - os: linux
      r: release
      env:
        - R_CODECOV=true
    - os: linux
      r: devel
    - os: linux
      r: oldrel
    - os: osx
      osx_image: xcode8.3

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then Rscript -e 'covr::codecov()'; fi

env:
  global:
    - NOT_CRAN: true
    - R_BUILD_ARGS="--resave-data --compact-vignettes=gs+qpdf"
    - R_CHECK_ARGS="--as-cran --timings"
    - R_CHECK_TIME="TRUE"
    - R_CHECK_TESTS="TRUE"
    - _R_CHECK_TIMINGS_="0"
    - _R_CHECK_SYSTEM_CLOCK_="0"
